name: aima
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # pacote para acessar galeria e tirar fotos
  image_picker: ^0.7.4
  # pacote do calendario
  table_calendar: ^3.0.0
  # pacote para formatar data
  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0
  # pacote para preferencias do user
  shared_preferences: ^2.0.5
  sqflite: ^2.0.2
  provider: ^6.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sqlite_viewer: ^1.0.5
  firebase_core: ^1.17.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # pacote para alterar icon do app
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
          style: normal
